title: "HTB Academy CJCA Writeups"
description: "Hands-on cybersecurity writeups and notes from the HTB Academy CJCA path."

theme: jekyll-theme-midnight   # or cayman / midnight / slate

show_downloads: false
